### ISSUE TITLE
Better function definition + type hints

### ISSUE THREAD

**Issue by BlazeWasHere** [PloxHost-LLC/community-bot#153]
https://github.com/PloxHost-LLC/community-bot/blob/71a17f108684c2692f9e402a09913af1d11cceb1/cogs/economy.py#L17-L26

There is no need to make this an async function as there are no calls to async functions within `GiveNewCard(...)`

Also, better to be type hinting with nested types e.g `list[str]` rather than `list` which expands to `list[unknown]`. 

In Python <3.9:
```py
from typing import List
List[_T]
```

In Python 3.9+:
```py
list[_T]
```

Where `_T` is the type of the values in the list.

**Comment by FluxedScript** [comment]
Solved your async/await issue. It wouldn't be suitable for this project to type Lists. If this was a library/package/module then sure but there is no need for typing in this project.
